# Dockerfile v1.03.01
# Last updated 12-20-18 by Jason Xie
#
# The base image can be found here. This version features the last use of python 3.6
# http://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html
FROM jupyter/base-notebook:9e8682c9ea54

# RUN pip install -U pip Cython

# Without switching users, there are some permissions problems
USER root

