FROM gitpod/workspace-full:latest

USER gitpod

# Install custom tools, runtime, etc.
RUN pip3 install -U pip Cython

# Without switching users, there are some permissions problems
USER root

# Install necessary libraries to successfully install pdia requirements
RUN apt-get update && apt-get install -y --no-install-recommends\
    python3-dev \
    unixodbc-dev \
    freetds-dev \
    libopenblas-dev \
    g++ 

# Give back control
USER root
