FROM gitpod/workspace-full:latest

USER gitpod

# Install custom tools, runtime, etc.
RUN pip3 install -U pip Cython

# Without switching users, there are some permissions problems
USER root

# Copy necessary files from this directory into temporary folder
# Use the .dockerignore file to designate exceptions
COPY . ./src/

# Move into the temporary folder for installation
WORKDIR ./src

# Install necessary libraries to successfully install pdia requirements
RUN apt-get update && apt-get install -y --no-install-recommends\
    python3-dev \
    unixodbc-dev \
    freetds-dev \
    libopenblas-dev \
    git \
    g++ 
    # && \
    # rm -rf /var/lib/apt/lists/*

# Momentarily switch to the normal user to install requirements from PyPi
# USER gitpod
RUN pip3 install git+https://github.com/pymssql/pymssql.git && \
    pip3 install -r requirements.txt
# USER root

# Run setup and install punkt module as described in Wiki
# Clean up unnecessary files
RUN python3 setup.py install && \
    conda install -c conda-forge pyarrow && \
    conda clean -tipsy
# Exit and delete temporary folder
WORKDIR ..
# RUN rm -d -r src/

USER gitpod
# Apply user-specific settings
# ENV ...

# Give back control
USER root
